# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12.18.1

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm ci
          - npm run ng build --prod
#          - npm test
        artifacts:
          - dist/**
    - step: 
        name: Deploy to test
        deployment: test
        script:
          - pipe: atlassian/aws-s3-deploy:0.4.4
            variables:
              S3_BUCKET: 'va-cedar-cdn/hello-world/test'
              LOCAL_PATH: 'dist/vacedar'
